### ISSUE TITLE
Querying for EFO_0000408 gives 404.

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/gwas-ui#122]
https://www.ebi.ac.uk/gwas/rest/api/efoTraits/EFO_0000408/

**Comment by DSuveges** [comment]
Through the REST API only those EFOs can be accessed that were assigned to at least one association. Your trait of interest [EFO_0000408](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0000408) is "disease", which is a very high level trait definition, with no direct association, therefore the 404 response.

**Comment by ramiromagno** [comment]
I thought I could query with any EFO and that the server would return all associations related to that trait or any child term.

So that means I cannot make more degenerate queries, e.g. encompassing all traits that are diseases?

**Comment by DSuveges** [comment]
> So that means I cannot make more degenerate queries, e.g. encompassing all traits that are diseases?

Yes, that's correct. 

However, [OLS](https://www.ebi.ac.uk/ols/index) (Ontology Lookup Service) (also developed by the SPOT team) provides direct link between all related ontology terms. So, depending your use case, you can retrieve all child EFO terms of "disease" then use them to fetch GWAS associations. (It might not necessarily the most efficient way to do it though.)

`curl -L 'http://www.ebi.ac.uk/ols/api/ontologies/efo/descendants?id=EFO_0000408' -i -H 'Accept: application/json'`

You can find more information on the REST API of OLS here: `https://www.ebi.ac.uk/ols/docs/api`

Please don't hesitate to contact us if you have further question. Also if you have a plan or scientific question in mind, we can help to design the most efficient way to retrieve data from our databases.

**Comment by twhetzel** [comment]
@ramiromagno since there are a large number of terms that are children of disease, it may be useful to start with the GWAS association download file [1] and then query OLS to see if the term is a descendant of "disease" and then query the GWAS REST API

Is this for a data mining project or for use in an application?

[1] https://www.ebi.ac.uk/gwas/docs/file-downloads

**Comment by ramiromagno** [comment]
I am developing an R client for the GWAS REST API.

So I was wondering if it would be possible to query, let's say, all association studies whose trait is cancer or an EFO child term thereof.

**Comment by ramiromagno** [comment]
@twhetzel: in the download file you mentioned, each row is an association? What combination of variables (columns) uniquely identifies each row?
