### ISSUE TITLE
Migrating resources off rawgit

### ISSUE THREAD

**Issue by ar0ch** [EBISPOT/gwas-ui#154]
There are resources linked through the GWAS Catalog site that make use rawgit.com.  Rawgit shutdown a little over year ago (Oct 2018) and as of end of October 2019 there is no guarantee that resources will continue to be served.  Indeed, several of the URIs currently are currently 404ing (e.g.: https://cdn.rawgit.com/wenzhixin/bootstrap-table/develop/dist/extensions/flat-json/bootstrap-table-flat-json.js).

I'm also not sure how many of these js libraries are even still in use on the website.  The below snippet appears on several pages (gene-page.html, efotrait-page.html, region-page.html, publication-page.html, summary-statistics-table.html, summary-statistics.html) and mixes different forks of the same library (Table Export).  However, I don't see any of their functions actually being used on the UI.

```html
<!--bootstrap-table-flat-json-->
    <script src="https://cdn.rawgit.com/wenzhixin/bootstrap-table/develop/dist/extensions/flat-json/bootstrap-table-flat-json.js"></script>
    <script src="https://cdn.rawgit.com/wenzhixin/bootstrap-table/develop/dist/extensions/multiple-sort/bootstrap-table-multiple-sort.js"></script>
    <script src="https://cdn.rawgit.com/wenzhixin/bootstrap-table/develop/dist/extensions/export/bootstrap-table-export.js"></script>
    <script src="https://cdn.rawgit.com/wenzhixin/09e218c884f4f380b68a/raw/5d258d2f78225a4ac1a72d54a34cc7976d630df1/jquery.base64.js"></script>
    <script src="https://cdn.rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js"></script>
```

**Comment by jstewart-ebi** [comment]
Deployed to snoopy.ebi.ac.uk:9580 for testing
