### ISSUE TITLE
Change link from GWAS Catalog UI to link to new GitHub repository for user requests/bug reporting

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/gwas-ui#173]
Change link from GWAS Catalog UI (on bottom of home page https://www.ebi.ac.uk/gwas/ with text "If you think you've found a bug, take a look at our known issues page") to link to new GitHub repository for feature requests from users and bug reporting

**Comment by twhetzel** [comment]
@eks-ebi available on Snoopy 9680 for testing

**Comment by eks-ebi** [comment]
@twhetzel Tested 2020-07-10 and looks good. Repository name also makes sense and the instructions on that GitHub page all seems to be straightforward for a user to work with
