### ISSUE TITLE
Create interactive links from the GWAS Catalog user interface to PGS Catalog

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/gwas-ui#174]
Create links from the publication, GWAS study and trait page to the relevant pages in the PGS Catalog.

GWAS Study page (https://www.ebi.ac.uk/gwas/studies/GCST003116) - add a link button "View in PGS Catalog" under "View in Europe PMC" with link to PGS Catalog endpoint https://rest-dot-pgs-catalog.appspot.com/rest/gwas/get_score_ids/GCST003116 - returns a list of PGS Score  IDs

Trait page (https://www.ebi.ac.uk/gwas/efotraits/EFO_0000378) - add a link button "Trait in PGS Catalog" under "Trait in Open Targets" with link to PGS Catalog endpoint - Search by EFO ID (using the parameter “trait_id”):  https://rest-dot-pgs-catalog.appspot.com/rest/score/search/?trait_id=EFO_0000378

Publication page (https://www.ebi.ac.uk/gwas/publications/29892016) - add a link button "View in PGS Catalog" under "View in Europe PMC" with link to PGS Catalog search by PubMed ID (using the parameter “pmid”): https://rest-dot-pgs-catalog.appspot.com/rest/score/search/?pmid=29892016 - returns a list of PGS Score “objects”

**Comment by JalMacArthur** [comment]
EFO trait:
https://www.pgscatalog.org/trait/EFO_0000305/

From publication:
To see if a GWAS publication is in the Catalog (e.g. if it also developed a PGS) you can search using the PMID https://www.pgscatalog.org/rest/publication/search?pmid=25855707, if 'id' is in the response you can use it to point to a PGS Catalog page: http://pgscatalog.org/publication/PGP000001/

**Comment by twhetzel** [comment]
@smlmbrt do you have an example of a publication that is both in the GWAS Catalog and in the PGS Catalog?

**Comment by twhetzel** [comment]
@ens-lgil Can a PMID ever have more than one result, i.e. will `https://www.pgscatalog.org/rest/publication/search?pmid=25855707` always have a result with only one object?

**Comment by twhetzel** [comment]
@JalMacArthur this is ready to test on Snoopy 9680

**Comment by JalMacArthur** [comment]
@twhetzel I just tested this in Snoopy 9680
- The link from the trait page (tested EFO_0000305) works
- When I click on the button to link from the publication (PMID 29892016) and GWAS study (GCST004988) nothing happens
- The links appear on every trait, publication and study page, even if there is no relevant page in the PGS Catalog (e.g. GCST000148, EFO_0004863, 18239089). Is it possible to remove the link button if there is no relevant page in the PGS Catalog?

**Comment by twhetzel** [comment]
@JalMacArthur 
- For the publication (PMID 29892016) and GWAS study (GCST004988), can you try to clear your cache and try again please? These both work for me on Snoopy 9680


Yes, the display of the buttons can be dynamic depending on whether there is a matching entity in the PGS Catalog. I have the PGS REST endpoint for Traits[1] and Publications, is there one for Studies[2]?

[1] https://www.pgscatalog.org/rest/trait/EFO_0000305
[2] https://www.pgscatalog.org/rest/publication/search?pmid=25855707

**Comment by JalMacArthur** [comment]
@ens-lgil Is there an endpoint for the PGS Catalog that we can use to determine if a page exists for a GCST? Thanks

**Comment by twhetzel** [comment]
@ens-lgil can we also chat about the CORS set-up for the PGS Catalog?

**Comment by twhetzel** [comment]
@ens-lgil can we chat about how CORS is set-up on PGS or get some pointers from you on what I'll need to add to the call I am making from the GWAS Catalog to the PGS REST endpoints?

**Comment by twhetzel** [comment]
@JalMacArthur I've updated the buttons so that the Trait and Publication buttons in the GWAS Catalog with links to PGS display only if there is a matching page in PGS.

===============
TESTING

- Publication
PMID exists in GWAS & PGS - 29892016
PMID in GWAS only - 25533513

- Trait
Trait exists in GWAS & PGS - EFO_0000305
Trait in PGS only - EFO_0000714

- Study - the button display is not dynamic, waiting for information from PGS developer
Study exists in both GWAS & PGS - GCST003116
Study exists in GWAS only - GCST003117
===============

**Comment by JalMacArthur** [comment]
Tested above:

- On page http://snoopy.ebi.ac.uk:9680/gwas/publications/29892016 link to PGS Catalog doesn't appear and it should
- On page http://snoopy.ebi.ac.uk:9680/gwas/efotraits/EFO_0000305 link to PGS Catalog doesn't appear and it should

Note for GCST link to PGS Catalog does appear but is not dynamic (link always appears, whether in PGS Catalog or not).

**Comment by twhetzel** [comment]
NOTE: Do not include in the release until all buttons can be displayed dynamically based on if there is a matching entity in the PGS Catalog

**Comment by ens-lgil** [comment]
> @ens-lgil Can a PMID ever have more than one result, i.e. will `https://www.pgscatalog.org/rest/publication/search?pmid=25855707` always have a result with only one object?

@twhetzel, no it will always return 1 object when you search for a PMID.
The endpoint is setup by default to return a list of objects (as we do for each of our "search" endpoints), but a PMID is unique in our system

**Comment by ens-lgil** [comment]
> @ens-lgil Is there an endpoint for the PGS Catalog that we can use to determine if a page exists for a GCST? Thanks

@JalMacArthur, you can use the GCST endpoint: [https://www.pgscatalog.org/rest/#/Other%20endpoints/getGCST](https://www.pgscatalog.org/rest/#/Other%20endpoints/getGCST).
This will return an empty array if the GCST is not in the PGS Catalog

**Comment by ens-lgil** [comment]
> @ens-lgil can we chat about how CORS is set-up on PGS or get some pointers from you on what I'll need to add to the call I am making from the GWAS Catalog to the PGS REST endpoints?

I didn't setup CORS at the moment for the PGS REST API, but I can add the ebi URL on the CORS white list.
I am not an expert of CORS, therefore I am happy for any advice on it.

**Comment by twhetzel** [comment]
The button that links from a GWAS Catalog study page to a PGS Study page is now dynamically displayed.
