### ISSUE TITLE
Missing data in download (gwas-catalog-v1.0.3-studies-r20)

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/gwas-ui#175]
There are empty fields in the gwas-catalog-v1.0.3-studies-r20 download (the one with added fields to match the unpub download).  Some of them are meant to be empty right (?), but the mapped trait fields are also empty which surely isn't right.  Many of the other fields could also be populated.

**Comment by twhetzel** [comment]
This fix is merged into `dev` however, one more update to the Bamboo build plan "Data Release(prod)" for the Stage "GWAS File Export", step "Script - Execute new format studies and ancestry file generation" is needed. 

The parameters in the call needs to be updated to include `&efo=true` as below:
```
?q=text:*&pvalfilter=&orfilter=&betafilter=&datefilter=&genomicfilter=&traitfilter[]=&dateaddedfilter=&efo=true&facet=study_new_format
```

Add this after the Data release starting on 13-Jul-2020 completes successfully.

**Comment by twhetzel** [comment]
@ljwh2 I used this code to update and manually add the v1.0.3 studies download file to the data directory used by "wwwdev" so you can check out the file contents of this code update on the "wwwdev" site for the Search UI  file downloads.

**Comment by ljwh2** [comment]
Tested and looks good, ok to release
