### ISSUE TITLE
update links to harmonisation pipeline

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-ui#178]
Update all the links in the documentation to point to the new harmonisation repo: https://github.com/EBISPOT/gwas-sumstats-harmoniser

**Comment by ljwh2** [comment]
@jdhayhurst does this still need doing?

**Comment by jdhayhurst** [comment]
Yes this needs doing

**Comment by jdhayhurst** [comment]
updated documentation branch

**Comment by jdhayhurst** [comment]
checked in snoopy - all ok
