### ISSUE TITLE
Incorrect FTP link for published studies with SumStats

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-ui#180]
- Go to https://www.ebi.ac.uk/gwas/downloads/summary-statistics
- In the table of studies with Summary stats, search for 30093612
The FTP link is wrong or truncated? This may be with the table presentation code, but more likely with the code to create the table data

**Comment by twhetzel** [comment]
Fixed, submitted PR

**Comment by twhetzel** [comment]
To test, go to Snoopy 9680:
- click Summary Statistics
- click Available Studies
- In the table "List of published studies with summary statistics", search for O'Mara
- Click the link for the "FTP Download"
If the update here works, the link will now resolve to the FTP site for these summary statistics

**Comment by sprintell** [comment]
List of published studies with summary statistics table in snoopy differs from list in production, we need to know why
