### ISSUE TITLE
Performance of loading Summary stats page

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-ui#182]
- go to https://www.ebi.ac.uk/gwas/downloads/summary-statistics
The table for published studies with Summary stats data takes ~12 seconds to load. Curators have mentioned that the page has taken ~1 minute to load in some cases

The published studies table pulls data from both the Search UI data and from the SumStats REST API and there may have been some recent updates to the architecture for getting this data, any of which could be a cause in the slow response to load the table. As more studies with Summary stats are collected, I'd gather this table will become slower to load.

**Comment by ljwh2** [comment]
Need to add a "loading" icon for the prepublished table to make it behave the same as the published table

**Comment by ljwh2** [comment]
url for page where loading icon needed https://www.ebi.ac.uk/gwas/downloads/summary-statistics
