### ISSUE TITLE
Table of prepublished/unpublished summary stats cannot distinguish by ancestry / sample number

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/gwas-ui#184]
For prepublication submission 5f160ab1753ca500016c269a , GCP000030 , with 88 splits:
there is no way to differentiate studies with the same trait, conducted in different ancestries. 

![Screenshot 2020-08-19 at 10.42.22.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/6eaca25e-66af-4e5d-b14d-8211fca76e2d)

https://www.ebi.ac.uk/gwas/downloads/summary-statistics

The same issue would arise for same-trait studies with different sample numbers. 

Solution: an additional column for the study tag and/or ancestry category / number of individuals. 

Could also be useful in the published summary statistics table.

**Comment by sajo-ebi** [comment]
Have added the columns in Dev environment (http://snoopy.ebi.ac.uk:9680/gwas/downloads/summary-statistics)  @ljwh2 please verify if it looks okay

**Comment by ljwh2** [comment]
@earlEBI could you please verify

**Comment by earlEBI** [comment]
Study tag, ancestry and sample number are now all in the prepub table by default.
Could make 'study tag' an optional column @ljwh2? But either way, yes, issue resolved.

![Screenshot 2021-01-14 at 09 16 24](https://user-images.githubusercontent.com/61545198/104569986-47ac2f00-5649-11eb-8641-104567884baf.png)

**Comment by ljwh2** [comment]
@earlEBI confirm we don't need to include study tag here

@sajo-ebi there may be instances where there is more than one ancestry in the sample tab for the same study. Can you confirm whether this is accounted for? Ideally these should be represented with the different ancestries separated by pipes and the sum of the individuals in the "no. of individuals" column. @earlEBI can provide an example of a metadata template and how it should look in the UI.

**Comment by earlEBI** [comment]
@sajo-ebi Hi, here is an example template of a study with 3 separate ancestry sample rows. 

![Screenshot 2021-01-14 at 11 13 05](https://user-images.githubusercontent.com/61545198/104583808-7fbb6e00-5659-11eb-9de9-fec3c95e7a53.png)

This should appear as:

![Screenshot 2021-01-14 at 11 12 04](https://user-images.githubusercontent.com/61545198/104583707-60244580-5659-11eb-9d13-fbcb349f5aa0.png)


[ancestry_test_template.xlsx](https://github.com/EBISPOT/gwas-ui/files/5814006/ancestry_test_template.xlsx)

**Comment by sajo-ebi** [comment]
@ljwh2 @earlEBI  I will look in to the updates provided by you & accommodate the changes as mentioned

**Comment by sajo-ebi** [comment]
@ljwh2 @earlEBI I have verified the page the above mentioned scenario is already handled & have also removed study tag from the table , please find the snapshot
![Issue_184](https://user-images.githubusercontent.com/77010716/104739179-56284280-573e-11eb-87e9-391c93032191.PNG)
