### ISSUE TITLE
ftp links need to constructed using the new nested structure

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-ui#197]
All of the ftp links that are generated in the the search UI need to be account for the new structure when they are made.
Currently ftp links are generated using the path to the summary stats directory `summary_statistics/` joined to a directory name composed of `Author_pmid_gcst/`. Instead, it should be  `summary_statistics/` joined to a directory name composed of the the correct bin (range of 1000, starting at 1) for that gcst e.g. `GCST001001-GCST002000/` joined to a directory for the study, e.g. `GCST001234/`.

**Comment by jdhayhurst** [comment]
Validation failed even when I set the association threshold to 1:
```
(INFO): file type description: ASCII text (gzip compressed data, was "23andMe_SexGWAS_AllSamples.assoc.top10k_gwascat.tsv", last modified: Fri Jan 22 09:33:16 2021, from Unix)
  (INFO): md5: c4efcd6263d6dcdeac2fe1bd55d1b2c9
  (INFO): Validating file extension...
  (INFO): Validating headers...
  (ERROR): Required headers: ('p_value', 'chromosome', 'base_pair_location', 'variant_id') are not in the file header: ['variant_id' 'effect_allele' 'other_allele' 'N' 'beta' 'standard_error'
   'p_value' 'effect_allele_frequency' 'imp_rsqr' 'chrom'
   'base_pair_location']
  (INFO): Validating file for squareness...
  (INFO): Validating rows...
  (INFO): Validating data...
  (ERROR): {row: 3, column: "effect_allele"}: "I" does not match the pattern "^[ACTGNactgn]+$"
  (INFO): File is invalid - 1 bad rows, limit set to 1
  (INFO): VALIDATION FAILED
```
so the two errors are there's no "chromosome" column - it's written is as "chrom". The other error is that there are allele values given as "I"- which is probably for an insertion.

**Comment by jdhayhurst** [comment]
old structure (completely flat):

```
summary_statistics
+-- GCST...(left to preserve paths)
+-- author_pmid_gcst...(left to preserve paths)
```

New structure - bins of 1000 gcsts (numbers below are for illustrative purposes only!):
```
summary_statistics
+-- GCST001-GCST002
|   +-- GCST001
|   +-- GCST002
+-- GCST003-GCST004
|   +-- GCST003
|   +-- GCST004
+-- GCST005-GCST006
|   +-- GCST005
+-- GCST...(left to preserve paths)
+-- author_pmid_gcst...(left to preserve paths)
```

A real-life driectory would look like `GCST001001-GCST002000`

**Comment by jdhayhurst** [comment]
python function for creating range:
```
def get_gcst_range(gcst):
    # integer part of id
    number_part = int(gcst.split("GCST")[1])
    # round down to nearest 1000 and + 1
    floor = int(np.fix(number_part / range_size) * range_size) + 1
    # round up to nearest 1000
    upper = floor + (range_size -1)
    # put it all together
    range_str = "GCST{f}-GCST{u}".format(f=str(floor).zfill(6), u=str(upper).zfill(6))
    return range_str
```

**Comment by jdhayhurst** [comment]
@sajo-ebi I noticed that it's important to modify the function slightly to:

```
def get_gcst_range(gcst):
    number_part = int(gcst.split("GCST")[1]) - 1
    floor = int(np.fix(number_part / RANGE_SIZE) * RANGE_SIZE) + 1
    upper = floor + (RANGE_SIZE -1)
    range_str = "GCST{f}-GCST{u}".format(f=str(floor).zfill(6), u=str(upper).zfill(6))
    return range_str   
```

Notice the "-1" in the `number_part` calculation, this is because we start our ranges at 1 and not 0. So if we have GCST001000 this should go into GCST000001-GCST001000 (which it won't do unless we subtract 1 from 1000 and then find the floor).

**Comment by jdhayhurst** [comment]
Hi @sajo-ebi 

There's two things:

1) the links should be like this: `<ftp_base>/summary_statistics/GCST004001-GCST005000/GCST004420`. The way you have it currently is like this: `<ftp_base>/summary_statistics/GCST004001-GCST005000/Ahola-OlliAV_27989323_GCST004420`
2) the links also need to be updated on this page: gwas/studies/<id>

**Comment by sajo-ebi** [comment]
Changes have been deployed to Snoopy & have been validated by James, it is working fine.
