### ISSUE TITLE
Change ftp link from search Ui to http protocol 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-ui#218]
Google chrome (used by most GWAS Catalog users) no longer support ftp:// .... urls in broser , this will fix the problem

**Comment by jdhayhurst** [comment]
Additionally, the links need updating on the “study” tables on the pages: 
- gwas/publications/<id> 
- gwas/efotraits/<id>
- gwas/genes/<id>
- gwas/regions/<id>
- gwas/variants/<id> 
- gwas/studies/<id> (in the “study information” table)
