### ISSUE TITLE
As a user, when I search for a GCST in the GWAS Cat UI, a study snippet is returned

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-ui#231]
When a search is made, https://www.ebi.ac.uk/gwas/search?query=1 the results are returned in snippets, which represent the different solr documents:

- variant
- publication
- trait
- gene

Currently, you can search for _published_ GCSTs because they are indexed in the publication solr documents. _Unpublished_ GCSTs are not indexed anywhere, so users cannot search for them. To address this, we want to add a new solr document type called study. In the first iteration this should include:

- GCST (indexed)
- publication/body of work title - depending on whether it is published/unpublished (not indexed)

We need to add a "study" type snippet to the search results (see @ljwh2 mockups) when users search for GCST accessions. This snippet will provide a link to the study pages e.g. https://www.ebi.ac.uk/gwas/studies/GCST006288 (published) and https://www.ebi.ac.uk/gwas/studies/GCST90002217 (unpublished)

For more info including mockups, solr endpoints, see https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/209

**Comment by ala-ebi** [comment]
Done
![image.png](https://images.zenhubusercontent.com/60190c8d2d567e0492e6fdd9/ea7a1f3c-f788-4851-ac61-c13b7019e1ad)
Summary stats icon and association count are hard coded and always set to 'true' and 30 respectively, will be removed before release of first iteration, and added back when they are provided in the Solr response.

**Comment by ljwh2** [comment]
Looks good. A couple of small things:

1. The link from " Click here for more information" links to FAQ page top of section A, whereas it should link specifically to FAQ A21. This could be fixed if easy to do (but it's the same already in production, so ok to release without fix if too time consuming)

2. I tested some different searches and managed to return a study snippet with no GCST (searching for "colorectal cancer"). I can't find out what this is (uncurated study maybe?) but it shouldn't appear in the search. 

![Screenshot 2021-07-22 at 09.24.05.png](https://images.zenhubusercontent.com/5e57ecb5d0668b3a20e94b9e/1e57df3b-f91c-48a9-be3d-1eb727de8448)

In the final version we only need studies to be returned by searching for GCST directly, not by other fields, maybe this would fix this issue.

**Comment by ljwh2** [comment]
Search behaviour specifications from other ticket: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/209

Searching for GCST should return a study (first), plus parent publication if available. It should only return an exact match for GCST, it should never return a list of GCSTs (e.g. by searching for a truncated/wildcard GCST or other GCSTs in same publication) .

Searching for PMID should ideally return PMID (first) plus all studies, but this is not necessary if it is a significant amount of work.

Searching by trait, variant, gene or region should not return studies.

**Comment by ala-ebi** [comment]
1. in which page is the 'Click here for more information' hyperlink?
2. changes are implemented. will be merged to dev with 1.

**Comment by ala-ebi** [comment]
changes are on dev http://snoopy.ebi.ac.uk:9680/gwas/search?query=GCST90002217
searching by pubmed is isnt there yet. we need the pubmedId field in Solr Study documents.

**Comment by ljwh2** [comment]
@ala-ebi All looks good

On reflection, searching for PMID does not need to return studies - this will make it consistent with other search entities.

**Comment by jdhayhurst** [comment]
hi @ala-ebi I've updated the solr doc to contain the following in the study document:
- association count: `associationCount` (int)
- summary statistics available?: `fullPvalueSet` (bool)
- study is part of publication?: `published` (bool)

The dev2 solr server has been updated.

**Comment by ala-ebi** [comment]
made use of associationCount and fullPvalueSet http://snoopy.ebi.ac.uk:9680/gwas/search?query=GCST001234

**Comment by ljwh2** [comment]
@ala-ebi @jdhayhurst Tested, looks fine to release. Note that this release is first version, future improvements including more meaningful info in the snippet and inclusion of embargoed studies is detailed here: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/209
