### ISSUE TITLE
Do you still have plans to answer my issues/questions?

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/gwas-ui#261]
Hi GWAS team,

8 out of the 9 issues still open in this repository are by myself. It's been a while since I opened them. Do you still have plans to reply?

Thanks!

**Comment by ljwh2** [comment]
hi Ramiro, apologies, as part of implementing some new management processes we cleaned up all the old tickets and I assumed that as these were so old they had been resolved or were no longer required, so moved them to the "icebox". We can look into them now, please let us know if anything is no longer required?

**Comment by ramiromagno** [comment]
Hi Laura,

Thanks for the reply. 

I had a quick look at the issues, and I think they're still relevant.

**Comment by ljwh2** [comment]
Queries now added to epic https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/830 and will be addressed

**Comment by ramiromagno** [comment]
That's a private workspace, is it not?

**Comment by ljwh2** [comment]
The separate tickets should still be public, they're now just gathered together in an epic for internal tracking
