### ISSUE TITLE
Technical Analysis of the GWAS UI front end code, widgets & DevOps/Infrastructure

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-ui#269]
- **Application Code:** In-depth analysis of the urls, js, jquery, HTML on the existing gwas ui application, and static the documentation pages 
- **Poor Presentation:** Ascertain causes of poor presentation, unnecessary line wrapping, whitespaces, overlapping texts and ... as reported here https://bit.ly/3ka9P1
- **Table Features:** Identify and document all dataTable features on the studies, publications, triats, variants, region, and genes pages     
- **New Framework or Not:** Evaluate possibility of modifying exisitng jquery code to solve the problems or justify the need if replacing with a new framework and custom js code logic, functions, and ... that might need to be re-written
- **Tabbed Detailed Pages:** Ascertain practicality of using tabs instead of accordion and scrolling sections
- **EBI Visual Framework:** Ascertain practicality of using EBI stylesheet and maintaining homogeneous look and feel
- **Scaleable loading and presentation of large datasets:** Analyse each page and identify all problem areas
- **Tehnologies and Dependencies:** listing the technologies, frameworks, and other major dependencies of the project (both existing and proposed).
- **Dependencies:** Determine dependencies that need to be updated or replaced in order to complete the project.
- **Strategy:** explore, and propose architecture, including tasks and technologies that will be used.
- **Widgets:** investigate the Locus Zoom Plot / Manhattan plot and feasibility of implementing the specified features
- Create Report

**DevOps/Infrastructure**
- Ascertain and document the devops implications of modifying existing code base or replacing with a new framework
- Investigate and describe effect of change in UI and Back end on existing devops strategy (CI/CD, different environments)
- Propose strategies and architecture, including tasks and technologies that will be used.
- Create Report

**Comment by ljwh2** [comment]
add link to documentation and then close

**Comment by ala-ebi** [comment]
https://docs.google.com/document/d/1f2tb-G8t_WsQ-nmOxgacWnwLAOUsCORgnd5pf7m25os/edit
