### ISSUE TITLE
New GWAS UI User Experience Design and Review

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-ui#270]
**User Flow Documentation** 
Sketch of GWAS Website User Flow to reveal how pages or sections within the app connect to each other (just for documentation purposes)

**Low Fidelity Mockups**
Sketches of new general appearance and presentation, make it easier to communicate and establish contracts with the developer

**Comment by ljwh2** [comment]
@ljwh2 to review

**Comment by sprintell** [comment]
![home-page-1.png](https://images.zenhubusercontent.com/5f0f4126d974dfe9149c1910/2fa6e9fa-55f2-4cf4-9f1d-9a6e3d597dcb)![search-page.png](https://images.zenhubusercontent.com/5f0f4126d974dfe9149c1910/75e602d4-8223-49e0-be4e-84dfa2eb15fa)![details-page-1.png](https://images.zenhubusercontent.com/5f0f4126d974dfe9149c1910/6e869e13-d658-4da3-b82e-7b6952525046)

**Comment by sprintell** [comment]
https://docs.google.com/presentation/d/1X3MW_CeUsqmy4wxSHI7FCZOHoXOm9RJP8A1MvdyTEr4/edit?pli=1#slide=id.g1d0e8727d0e_0_1270
