### ISSUE TITLE
Publication Associations - API endpoint to get all association resources associated to a given publication.

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-ui#282]
As developer
I want an api endpoint
So that when I send a GET request, hateoas, paginated list of all associations associated to a given publication in the database is returned in JSON Format

Management Rules:
Rule 1: Endpoint - /v2/publications/{publicationsId}/associations
Rule 2: HTTP Request Method - GET
Rule 3: HATEOAS, with filer, sorting, pagination, and sizing
Rule 4: Endpoint should accept filter, and sort parameters as in /associations?accession=...&page=0&size=20&sort=...

Rule 5: Search filter should be available for: variant-risk-allele, p-value-annotation, mapped-gene, reported-trait, efo-trait, background, accession, location

Rule 6: Sort feature should be available for: p-value, p-value-annotation, raf, or, beta, location, Optional Sorts (reported-trait, efo-trait, background-trait)

Rule 7: Returned Study Json entity must include: Variant and risk allele, P-value, P-value annotation, RAF, OR, Beta, CI, Mapped gene, Reported trait, Trait(s), Background trait(s) , Study accession, Location

Acceptance Tests:
Given no parameter
When the front end sends a GET request to the endpoint
Hateoas compliant list of studies is returned in the specified JSON Format

Given sorting, pagination, and/or some search and filter parameters
When the front end sends a GET request to thesame endpoint
Hateoas compliant filtered list of studies satisfying the conditions in the url parameter must be returned

**Comment by sajo-ebi** [comment]
@sprintell The Location field is not indexed in Solr hence can't be searched & sorted

**Comment by sajo-ebi** [comment]
@sprintell the Pvalue Annotation is a mutivalue field with values like '(Total Mortality)' , do we need to sort this? As we will need to create a new field in Solr to copy text & then sort on that

**Comment by sajo-ebi** [comment]
raf field is stored a textfield in Solr , so in order to sort we need to copy in to new field & save it as numeric & reindex the SOlr , can do this based on priority as it will require Solr indexer changes

**Comment by sajo-ebi** [comment]
@ala-ebi the API details are below -:

Uri -:  [http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/publications/{publicationId}/associations](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/publications/{publicationId}/associations)

Search fields -:

`@JsonProperty("riskAllele")
    private String riskAllele;

    @JsonProperty("pValueAnnotation")
    private String pValueAnnotation;

    @JsonProperty("mappedGene")
    private String mappedGene;

    @JsonProperty("accessionId")
    private String accessionId;

    @JsonProperty("reportedTrait")
    private String reportedTrait;

    @JsonProperty("efoTrait")
    private String efoTrait;

    @JsonProperty("bgTrait")
    private String bgTrait;

    @JsonProperty("location")
    private String location;`

Sort fields -:

`pvalue, raf , beta, or`
