### ISSUE TITLE
Fix header on smaller screens

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/gwas-ui#349]
On smaller screens, the header gets big and covers part of the home page on LABS

**Comment by ljwh2** [comment]
This works ok most of the tie, but when shrinking the screen there is a point where the header disappears and reappears again, see screen recording attached https://images.zenhubusercontent.com/138699369/6314cc7a-db53-4024-9139-9ea1d3561a14/header_size.mov

**Comment by sprintell** [comment]
@ljwh2 pls test.

**Comment by ljwh2** [comment]
confirming this looks good to me @ala-ebi, closing ticket
