### ISSUE TITLE
Export contents of data tables in new UI 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/gwas-ui#351]
As a user, I want to be able to be able to export contents of the data tables (e.g. Studies, Associations, Sumstats) from the new UI pages, as .tsv file (see note). I want to be able to do this from all tables displayed in the UI. 

This feature MUST include the ability to export the full (unpaginated) contents of each table. 

This feature SHOULD allow users to export filtered table contents as they can see on the screen (e.g. after applying a sort or search option)

Note the old UI export functionality exported .csv files, but since the full Catalog downloads are in .tsv format, for consistency it would be better for the table exports to be tsv as well. But if there is some technical reason why they should be csv, that's fine.

**Comment by sajo-ebi** [comment]
@ala-ebi the API details for download are as follows -:

EFO Page
[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/efotraits//studies/download?includeBgTraits=false&includeChildTraits=true](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/efotraits/%3CefoId%3E/studies/download?includeBgTraits=false&includeChildTraits=true)

[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/efotraits//associations/download?includeBgTraits=false&includeChildTraits=true](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/efotraits/%3CefoId%3E/associations/download?includeBgTraits=false&includeChildTraits=true)

Variant Page
[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/variants//studies/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/variants/%3CvariantId%3E/studies/download)

[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/variants//associations/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/variants/%3CvariantId%3E/associations/download)

[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/variants//traits/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/variants/%3CvariantId%3E/traits/download)

Gene Page
[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/genes//studies/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/genes/%3CgeneId%3E/studies/download)

[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/genes//associations/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/genes/%3CgeneId%3E/associations/download)

[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/genes//traits/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/genes/%3CgeneId%3E/traits/download)

**Comment by sajo-ebi** [comment]
@ala-ebi

Publications Page
[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/publications//studies/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/publications/%3CpublicationId%3E/studies/download)

[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/publications//associations/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/publications/%3CpublicationId%3E/associations/download)

Region Page
[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/regions//studies/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/regions/%3CregionId%3E/studies/download)

[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/regions//associations/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/regions/%3CregionId%3E/associations/download)

[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/regions//traits/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/regions/%3CregionId%3E/traits/download)

Studies Page
[http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/studies//associations/download](http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/studies/%3CstudyId%3E/associations/download)

Summary Stats Page
summaryStatistics

http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/summaryStatistics/studies/download

**Comment by ljwh2** [comment]
Tested in Snoopy and found a few issues: 

Sumstats tables: 
There is no export from sumstats table on any page. 
I also noticed the "agreedToCc0" column is included in the studies table export, but does not appear in the column visibility options for any table. This should be included in the column visibility options for the sumstats table export. 

Sumstats download page:
Could not get table export to work - just spinning forever
Even though no work has been done on the loading for the prepub table, it would be nice if we can change the buttons so they match the first table.

Trait page:
If possible, the export should reflect the child & background trait options selected on the page.

**Comment by Santhi1901** [comment]
- Export not including child traits
         It is confusing when it says, for eg: http://gwas-snoopy.ebi.ac.uk:9780/gwas/efotraits/EFO_0005278 Associations 35839 and when you 
         export, only 11 associations are there.

- The sumstats table not having the export option

**Comment by ljwh2** [comment]
For exporting child/background traits, I think something has got mixed up, it is exporting the opposite of what is displayed on screen. For example on the page for asthma: http://gwas-snoopy.ebi.ac.uk:9780/gwas/efotraits/MONDO_0004979

When you load the page the options are set to
Bkg traits NO
child traits YES
Displays 3288 assoc 
Downloads 2655 assoc

Change to
Bkg traits YES
child traits NO
Displays 2655 assoc 
Downloads 3288 assoc 

Change to Bkg traits YES
child traits YES
Displays 3590 assoc 
Downloads 3590 assoc (correct)

**Comment by ala-ebi** [comment]
fixed inverted child/bg filters.
added export to ss table
