### ISSUE TITLE
Tidy up Search UI

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/gwas-ui#365]

**Comment by ala-ebi** [comment]
- [ ] need to add cc0 to studies with ss, hidden by default
- [ ] check calls to trait API and make sure they include child and bg trait values
- [ ] the ss table for unpublished studies still uses the old table UI, needs to change
- [ ] do last comment on 352 and do 1036
- [ ] confirm goci #1020
- [ ] table export doesnt pass search params

**Comment by ala-ebi** [comment]
SS table for unpublished studies: the corresponding REST API doesnt support pagination, needs to be handled before changing the UI

**Comment by sprintell** [comment]
@ala-ebi to create two new tickets ...
