### ISSUE TITLE
What is a well-formed association ID?

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/gwas-ui#77]
What is a well-formed association ID?

Does it just need to be an 8 digit number? (e.g., `16510553`, as provided in the doc example: [Retrieve an association](https://www.ebi.ac.uk/gwas/rest/docs/api#_retrieve_an_association))

It's useful to know this when writing an API client so that we can check user's query ID before submitting the request.

**Comment by cmalangone** [comment]
Currently, the ID is a number and it might be longer than 8 digit.
We support HATEOAS. You can navigate the site's REST interfaces dynamically. 
For example the section below, show how to access to the association.
_links: {
self: {
href: "https://www.ebi.ac.uk/gwas/rest/api/associations/16601"
},
association: {
href: "https://www.ebi.ac.uk/gwas/rest/api/associations/16601{?projection}",
templated: true
},
study: {
href: "https://www.ebi.ac.uk/gwas/rest/api/associations/16601/study"
},
efoTraits: {
href: "https://www.ebi.ac.uk/gwas/rest/api/associations/16601/efoTraits"
},
snps: {
href: "https://www.ebi.ac.uk/gwas/rest/api/associations/16601/snps"
}
}

**Comment by cmalangone** [comment]
Please find more details about the status of this issue here:
https://www.ebi.ac.uk/panda/jira/browse/GOCI-2444

**Comment by ramiromagno** [comment]
Ok, thanks!
