### ISSUE TITLE
Is the authors' list available through the REST API?

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/gwas-ui#78]
For example, in the web version of the Catalog we can see the authors of the study `GCST000854`:

```
Perlis RH, Huang J, Purcell S, Fava M, Rush AJ, Sullivan PF, Hamilton SP, McMahon FJ,
Schulze TG, Potash JB, Zandi PP, Willour VL, Penninx BW, Boomsma DI, Vogelzangs N,
Middeldorp CM, Rietschel M, Nöthen M, Cichon S, Gurling H, Bass N, McQuillin A,
Hamshere M, Wellcome Trust Case Control Consortium Bipolar Disorder Group,
Craddock N, Sklar P, Smoller JW
```

Is this information available through the REST API? Requesting [https://www.ebi.ac.uk/gwas/rest/api/studies/GCST000854](https://www.ebi.ac.uk/gwas/rest/api/studies/GCST000854) does not seem to return this field but only the first author.

**Comment by cmalangone** [comment]
Please find more details about the status of this issue here:
https://www.ebi.ac.uk/panda/jira/browse/GOCI-2445
