### ISSUE TITLE
500 error when passing too large numbers in genomic range

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/gwas-ui#80]
```bash
curl 'https://www.ebi.ac.uk/gwas/rest/api/snpLocation/X:95000000-10000000000' -i -H 'Accept: application/json'
```
returns:

```
HTTP/2 500 
server: Apache-Coyote/1.1
content-type: application/json;charset=UTF-8
strict-transport-security: max-age=0
date: Fri, 12 Oct 2018 18:47:50 GMT

{"timestamp":1539370071557,"status":500,"error":"Internal Server Error","exception":"java.lang.NumberFormatException","message":"For input string: \"10000000000\"","path":"/gwas/rest/api/snpLocation/X:95000000-10000000000"}
```

**Comment by ramiromagno** [comment]
Related to the issue above:

```
curl 'https://www.ebi.ac.uk/gwas/rest/api/snpLocation/non-existant-chromosome:1-20000' -i -H 'Accept: application/json'
```

gives a 200 response for a 'non-existant chromosome' :smile: :

```
HTTP/2 200 
server: Apache-Coyote/1.1
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-type: application/json;charset=UTF-8
strict-transport-security: max-age=0
date: Fri, 12 Oct 2018 18:53:20 GMT
x-application-context: application
expires: 0
x-xss-protection: 1; mode=block
pragma: no-cache
x-content-type-options: nosniff
x-frame-options: DENY

{
  "_links" : {
    "self" : {
      "href" : "https://www.ebi.ac.uk/gwas/rest/api/snpLocation/non-existant-chromosome:1-20000"
    }
  },
  "page" : {
    "size" : 0,
    "totalElements" : 0,
    "totalPages" : 1,
    "number" : 0
  }
}⏎           
```

**Comment by ramiromagno** [comment]
Reversing the start and end positions of the range also gives a 200 response:

```
curl 'https://www.ebi.ac.uk/gwas/rest/api/snpLocation/X:20000-1' -i -H 'Accept: application/json'
```

```
HTTP/2 200 
server: Apache-Coyote/1.1
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-type: application/json;charset=UTF-8
strict-transport-security: max-age=0
date: Fri, 12 Oct 2018 18:55:46 GMT
x-application-context: application
expires: 0
x-xss-protection: 1; mode=block
pragma: no-cache
x-content-type-options: nosniff
x-frame-options: DENY

{
  "_links" : {
    "self" : {
      "href" : "https://www.ebi.ac.uk/gwas/rest/api/snpLocation/X:20000-1"
    }
  },
  "page" : {
    "size" : 0,
    "totalElements" : 0,
    "totalPages" : 1,
    "number" : 0
  }
}
```

**Comment by cmalangone** [comment]
Dear Ramiro,
we are aware about this issue. We have similar issue with other endpoints.
https://www.ebi.ac.uk/panda/jira/browse/GOCI-2278

I added to your case to this ticket.

**Comment by ramiromagno** [comment]
@cmalangone: FWIW, I do not think that the 500 response described above with large numbers is related to the original problem reported in [https://www.ebi.ac.uk/panda/jira/browse/GOCI-2278](https://www.ebi.ac.uk/panda/jira/browse/GOCI-2278). 

Indeed both return a 500 error but the first problem here reported shows that it is likely related to the type of number you chose to encode the positions internally, an `int` I guess (as the JSON response mentions `java.lang.NumberFormatException`). In Java an `int` is at most `2^31-1 = 2147483648`... which is below `10000000000` (used in the query example above)...

The other problem in [https://www.ebi.ac.uk/panda/jira/browse/GOCI-2278](https://www.ebi.ac.uk/panda/jira/browse/GOCI-2278) seems to be related with having to pack tons of information back to the requester...

So I guess you should not mix these two issues in the same ticket.

**Comment by cmalangone** [comment]
Agree with Ramiro
https://www.ebi.ac.uk/panda/jira/browse/GOCI-2446

**Comment by jstewart-ebi** [comment]
Fixed via JIRA goci-2446.
